/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buku_telp;
import Tabel.DataKontak;
import Tabel.TabelDataKontak;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author USER
 */
public class Kontak extends javax.swing.JFrame {

    private Connection koneksi;
    private Statement script;
    private TabelDataKontak ModelDataKontak;
    /**
     * Creates new form Kontak
     */
    public Kontak() {
        
        try {
for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
if ("Windows".equals(info.getName())) {
UIManager.setLookAndFeel(info.getClassName());
break;
}
}
}
catch (Exception ex) {
ex.getMessage();
}
        initComponents();
        
    ModelDataKontak = new TabelDataKontak();
    TKontak.setModel(ModelDataKontak);
    
    KoneksiDb();
    tampil( );
    bersih( );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        TxtTelp = new javax.swing.JTextField();
        Txtmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cari = new javax.swing.JComboBox<>();
        textcari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TKontak = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buku Telephone");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(230, 20, 190, 30);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(90, 0, 100, 70);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 10, 630, 70);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Kontak"));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nama");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 30, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Kontak");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 70, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 110, 50, 30);
        jPanel3.add(TxtNama);
        TxtNama.setBounds(70, 30, 180, 30);

        TxtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelpActionPerformed(evt);
            }
        });
        jPanel3.add(TxtTelp);
        TxtTelp.setBounds(70, 70, 180, 30);

        Txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtmailActionPerformed(evt);
            }
        });
        jPanel3.add(Txtmail);
        Txtmail.setBounds(70, 110, 180, 30);

        jLabel5.setText("Cari berdasarkan");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(440, 10, 120, 30);

        cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih salah satu--", "nama", "telephon", "email" }));
        jPanel3.add(cari);
        cari.setBounds(440, 50, 140, 30);

        textcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcariActionPerformed(evt);
            }
        });
        textcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textcariKeyReleased(evt);
            }
        });
        jPanel3.add(textcari);
        textcari.setBounds(440, 100, 140, 30);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(300, 30, 100, 100);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 100, 600, 180);

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setLayout(null);

        simpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel4.add(simpan);
        simpan.setBounds(20, 30, 100, 30);

        ubah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel4.add(ubah);
        ubah.setBounds(20, 80, 100, 30);

        hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel4.add(hapus);
        hapus.setBounds(20, 130, 100, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(480, 300, 130, 190);

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Kontak"));
        jPanel5.setLayout(null);

        TKontak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TKontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TKontakMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(TKontak);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 440, 160);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 300, 460, 190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 500);

        setSize(new java.awt.Dimension(637, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelpActionPerformed

    private void TxtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtmailActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        ubah();
    }//GEN-LAST:event_ubahActionPerformed

    private void TKontakMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TKontakMousePressed
        // TODO add your handling code here:
        tabel();
    }//GEN-LAST:event_TKontakMousePressed

    private void textcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textcariKeyReleased
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_textcariKeyReleased

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_simpanActionPerformed

    private void textcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kontak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TKontak;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtTelp;
    private javax.swing.JTextField Txtmail;
    private javax.swing.JComboBox<String> cari;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField textcari;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

private void KoneksiDb( ){ try{
Class.forName("com.mysql.jdbc.Driver");
koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_bukutelp", "root", "");
script = koneksi.createStatement( );
}
catch(SQLException ex){
System.err.print(ex);
}
catch(ClassNotFoundException ex){
System.err.print(ex);
}
}
    
private void tampil( ){
try{
int baris = TKontak.getRowCount( );
for(int i=0; i<baris; i++){
ModelDataKontak.delete(0, baris);
}

String sql = "select * from tb_kontak";
ResultSet rs = script.executeQuery(sql);

while (rs.next( )){
DataKontak kontak = new DataKontak( );

kontak.setNama(rs.getString(1));
kontak.setTelepon(rs.getString(2));
kontak.setE_mail(rs.getString(3));

ModelDataKontak.add(kontak);
}
}
catch(SQLException ex){
System.err.print(ex);
}
}

private void bersih( ){
TxtNama.setText(null);
TxtTelp.setText(null);
Txtmail.setText(null);
textcari.setText(null);
simpan.setEnabled(true);
ubah.setEnabled(false);
hapus.setEnabled(false);
}

private void tabel( ){
TKontak.getSelectionModel( ).addListSelectionListener(new ListSelectionListener( ) {

@Override
public void valueChanged(ListSelectionEvent e) {
int baris = TKontak.getSelectedRow( );

if(baris != -1){
DataKontak kontak = ModelDataKontak.get(baris);
TxtNama.setText(kontak.getNama( ));
TxtTelp.setText(kontak.getTelepon( ));
Txtmail.setText(kontak.getE_mail( ));
}
}
});
simpan.setEnabled(false);
ubah.setEnabled(true);
hapus.setEnabled(true);
}

private void simpan( ){
try{
String sql = "insert into tb_kontak values ("
+"'"+TxtNama.getText( )+"',"
+"'"+TxtTelp.getText( )+"',"
+"'"+Txtmail.getText( )+"'"
+")";

script.executeUpdate(sql);

tampil( );
JOptionPane.showMessageDialog(null, TxtNama.getText( )+" berhasil Disimpan");
bersih( );
}
catch(SQLException ex){

JOptionPane.showMessageDialog(this, "No Telepon sudah Ada");
bersih();

}
}

private void ubah( ){
int app;

if((app = JOptionPane.showConfirmDialog(null, "Ubah kontak"
+" ?","Perhatian",JOptionPane.YES_NO_OPTION))==0){
try{
String sql = "update tb_kontak set"
+" nama = '"+TxtNama.getText()+"',"
+" mail = '"+Txtmail.getText()+"' where"
+" telephon = '"+TxtTelp.getText()+"'";

script.executeUpdate(sql);

tampil( );
JOptionPane.showMessageDialog(null, "Kontak berhasil dirubah");
bersih( );
}
catch(SQLException ex){
System.err.print(ex);
}
}
}

private void hapus( ){
int app, bantu;

if((app = JOptionPane.showConfirmDialog(null, "Hapus data"
+" ?","Perhatian",JOptionPane.YES_NO_OPTION))==0){
try{
String sql = "delete from tb_kontak where"
+" nama = '"+TxtNama.getText()+"'";

bantu = script.executeUpdate(sql);

tampil( );
JOptionPane.showMessageDialog(null, "Kontak berhasil dihapus");
bersih( );
}
catch(SQLException ex){
System.err.print(ex);
}
}
}

private void cari( ){
int baris = TKontak.getRowCount( );
String bantu = cari.getSelectedItem( ).toString( );

for(int i=0; i<baris; i++){
ModelDataKontak.delete(i, baris);
}

try{
String sql = "select * from tb_kontak where "
+bantu+" like '%"+textcari.getText()+"%'";

ResultSet rs = script.executeQuery(sql);

while(rs.next( )){
DataKontak kontak = new DataKontak( );

kontak.setNama(rs.getString(1));
kontak.setTelepon(rs.getString(2));
kontak.setE_mail(rs.getString(3));

ModelDataKontak.add(kontak);
}
}
catch(SQLException ex){
System.err.print(ex);
}
}
}
